MAGIC_ENABLE = no
MAGIC_KEYCODE_ENABLE = no
BOOTMAGIC_ENABLE = no
EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes
KEYBOARD_SHARED_EP = yes

RGB_MATRIX_ENABLE = no

RGBLIGHT_ENABLE = yes
RGBLIGHT_DRIVER = SK6812

OPENRGB_ENABLE = no
